---
name: Build COBOL programs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GnuCOBOL compiler
      run: sudo apt-get install -y gnucobol

    - name: Build COBOL program
      run: make all

